# Generated by Django 4.2.4 on 2023-08-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pictures')),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
